spring:
  profiles:
    active: zhou
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.89.212:3306/securitydb?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: security
    password: Xplusplus-root-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  context-path: /security
  port: 9000
